// pagination-app-react/src/Components/CasesTable.js
import React, {Component} from 'react'
import './CasesTable.css'

const TableHeader = () => {
    return(
        <thead className="header">
            <tr>
                <td>Case ID</td>
                <td>Patient Name</td>
                <td>Type</td>
                <td>Clinician</td>
                <td>Status</td>
                <td>Last Updated</td>
            </tr>
        </thead>
    )
}

class CasesTable extends Component {
    constructor(props) {
        super();
        this.state = {
            pageData: props.casesData,
            page: 0,
            perPage: 10,
        };
        this.goTo = this.goTo.bind(this);
    }
      goTo(e) {
        this.setState(state => ({
            page: e
          }));
      }
    render() {
        
        //table body component -------------------------------------------------------------
        let {pageData, page, perPage} = this.state
        let pageNumber = this.state.page
        let totalPages = Math.ceil(this.props.casesData.length/perPage)
        let from = page * perPage;
        let to = (page + 1) * perPage;
        let displayData = pageData.slice(from, to)
        const cases = displayData.map((cases, index) => {
            return(
                <tr key={index}>
                    <td>{'SP-'+cases.id}</td>
                    <td>{cases.name}</td>
                    <td>{cases.type}</td>
                    <td>{cases.doctor}</td>
                    <td>
                        {<i className={this.props.tagColor[cases.status]}></i>}
                        {cases.status}
                    </td>
                    <td>{cases.lastUpdated}</td>
                </tr>
            )
        })
        //table body component -------------------------------------------------------------

        return(
            <div>

                <table>
                    <TableHeader />
                    <tbody>{cases}</tbody>
                </table>

                <div className="pagination">

{/* previous button */}
                    <div style={{float:'left'}}>{pageNumber > 0
                        ? <button className="previous" onClick={(e) => this.goTo(pageNumber-1)}>
                            <i className="material-icons">navigate_before</i>
                        </button>
                        : <button className="previous" disabled>
                            <i className="material-icons">navigate_before</i>
                        </button>
                    }
                    </div>

{/* first page */}
                    <button className="pgBlock" onClick={(e) => this.goTo(0)}>1</button>

{/* second page */}
                    <div style={{float:'left'}}>{pageNumber === totalPages-1 || pageNumber === 0
                        ? <button className="pgBlock" onClick={(e) => this.goTo(1)}>2</button>
                        : <div className="pgBlock">...</div>}
                    </div>

{/* current page */}
                    <div className="pgBlock">{pageNumber === totalPages-1 || pageNumber === 0 ? <div>...</div> : <div>{page+1}</div>}</div>

{/* last but one page */}
                    <div style={{float:'left'}}>{pageNumber === totalPages-1 || pageNumber === 0
                        ? <button className="pgBlock" onClick={(e) => this.goTo(totalPages-2)}>{totalPages-1}</button>
                        : <div className="pgBlock">...</div>}
                    </div>

{/* last page */}
                    <button className="pgBlock" onClick={(e) => this.goTo(totalPages-1)}>{totalPages}</button>

{/* next button */}
                    <div style={{float:'left'}}>{pageNumber < totalPages-1
                        ? <button className="next" onClick={(e) => this.goTo(pageNumber+1)}>
                            <i className="material-icons">navigate_next</i>
                        </button>
                        : <button className="next" disabled>
                            <i className="material-icons">navigate_next</i>
                        </button>
                    }
                    </div>
                    
                </div>

            </div>
        )
    }
}

export default CasesTable

// pagination-app-vue/src/components/CasesTable.vue
<template>
  <div id="cases-table">
    <table>
      <thead class="header">
        <tr>
          <td>Case ID</td>
          <td>Patient Name</td>
          <td>Type</td>
          <td>Clinician</td>
          <td>Status</td>
          <td>Last Updated</td>
        </tr>
      </thead>
      <tbody>
        <tr v-for="pages in display" :key="pages.id">
          <td>{{'SP-'+pages.id}}</td>
          <td>{{pages.name}}</td>
          <td>{{pages.type}}</td>
          <td>{{pages.doctor}}</td>
          <td>
            <div v-if="pages.status=='Closed'">
              <i class="greenTag"></i>
            </div>
            <div v-else-if="pages.status=='Open'">
              <i class="yellowTag"></i>
            </div>
            <div v-else>
              <i class="redTag"></i>
            </div>
            {{pages.status}}
          </td>
          <td>{{pages.lastUpdated}}</td>
        </tr>
      </tbody>
    </table>
    <div class="pagination">
      <div style="float:left">
        <button v-if="page!= 0" class="previous" @click="page--">
          <i class="material-icons" style="font-size: 1.5rem;">navigate_before</i>
        </button>
        <button v-else class="previous" disabled>
          <i class="material-icons" style="font-size: 1.5rem;">navigate_before</i>
        </button>
      </div>
      <button class="pgBlock" v-on:click="page=0">1</button>
      <button class="pgBlock" v-on:click="page=1">
        <span v-if="this.page==0 || this.page== totalPages-1">2</span>
        <span v-else>...</span>
      </button>
      
      <button class="pgBlock">
        <span v-if="this.page==0 || this.page== totalPages-1">...</span>
        <span v-else>{{page+1}}</span>
      </button>
      
      <button class="pgBlock" v-on:click="page=totalPages-2">
        <span v-if="this.page==0 || this.page== totalPages-1">{{totalPages-1}}</span>
        <span v-else>...</span>
      </button>
      
      <button class="pgBlock" v-on:click="page=totalPages-1">{{totalPages}}</button>
      <div style="float:left">
        <button v-if="page!= totalPages-1" class="next" @click="page++">
          <i class="material-icons">navigate_next</i>
        </button>
        <button v-else class="next" disabled>
          <i class="material-icons">navigate_next</i>
        </button>
      </div>
    </div>
  </div>
</template>

<script>
import json from "../cases.json";
export default {
  name: "cases-table",
  data() {
    return {
      cases: json,
      page: 0,
      perPage: 10
    };
  },
  methods: {
    pagination(cases) {
      let page = this.page;
      let perPage = this.perPage;
      let from = page * perPage;
      let to = (page + 1) * perPage;
      return cases.slice(from, to);
    }
  },
  computed: {
    display() {
      return this.pagination(this.cases);
    },
    totalPages() {
      return Math.ceil(this.cases.length / this.perPage);
    }
  }
};
</script>

<style scoped>
table {
  border-collapse: collapse;
  border-spacing: 0;
  width: 100%;
  font-size: 0.875rem;
  max-width: 100%;
}
header thead th {
  border-bottom: 2px solid #e6e6e6;
}

td {
  border-bottom: 1px solid #e6e6e6;
  text-align: left;
  padding: 0.75rem 0rem 0.75rem 4rem;
}

.header {
  color: #999999;
  text-align: left;
  padding: 0.5rem 0rem 0.5rem 4rem;
  font-weight: bold;
  background-color: #f2f2f2;
}
.redTag {
  margin: 5px 4px 4px 0px;
  border-radius: 4px;
  background-color: #FF5E5E;
  width: 0.5rem;
  height: 0.5rem;
  float: left;
}
.greenTag {
  margin: 5px 4px 4px 0px;
  border-radius: 4px;
  background-color: #2ECC71;
  width: 0.5rem;
  height: 0.5rem;
  float: left;
}
.yellowTag {
  margin: 5px 4px 4px 0px;
  border-radius: 4px;
  background-color: #F1C40F;
  width: 0.5rem;
  height: 0.5rem;
  float: left;
}
.pagination {
  float: right;
  color: #4a4a4a;
  margin-right: 2rem;
  margin-top: 3rem;
}
.pgBlock {
  float: left;
  padding: 0.5rem 0;
  font-size: 0.875rem;
  line-height: 1rem;
  border-style: solid;
  border-width: 2px 0px 2px 2px;
  border-color: #e6e6e6;
  width: 32px;
  cursor: pointer;
}
.next {
  padding: 0.125rem;
  border-radius: 0px 4px 4px 0px;
  border: 2px solid #e6e6e6;
  cursor: pointer;
}
.previous {
  padding: 0.125rem;
  border-radius: 4px 0px 0px 4px;
  border-style: solid;
  border-width: 2px 0px 2px 2px;
  border-color: #e6e6e6;
  cursor: pointer;
}
</style>
